version: '2'
services:
  rstudio:
    image: tonyjward/rstudio:scraping 
    ports:
      - "3838:8787"
    links:
      - selenium:selenium
    volumes:
      - ".:/home/rstudio"
    environment:
      - PASSWORD=letmein 
    entrypoint: ["Rscript", "Scraping/entrypointScraping.R"]
  selenium:
    image: selenium/standalone-chrome-debug:3.141.59
    ports:
      - "4445:4444"
    shm_size: 2G

# shm_size option required as chrome kept crashing
# https://github.com/elgalu/docker-selenium/issues/20#issuecomment-414495631
