version: '2'
services:
  rstudio:
    image: tonyjward/rstudio 
    ports:
      - "80:8787"
    links:
      - selenium:selenium
    volumes:
      - "./RCode:/home/rstudio/RCode"
      - "./ROutput:/home/rstudio/ROutput"
    environment:
      - PASSWORD=letmein 
  selenium:
    image: selenium/standalone-chrome-debug:3.14
    ports:
      - "4445:4444"
    shm_size: 2G

# shm_size option required as chrome kept crashing
# https://github.com/elgalu/docker-selenium/issues/20#issuecomment-414495631
