version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/ssl:/ssl/

  shiny:
    image: tonyjward/rstudio:shiny
    container_name: shiny
    restart: unless-stopped
    expose:
      - 3838
    volumes:
      - ./Shiny:/srv/shiny-server/
      - ./Shiny/shiny-server.conf:/etc/shiny-server/shiny-server.conf
      - ./Shiny/Logs:/var/log/shiny-server
